### ISSUE TITLE
xmlrpclib issue

### ISSUE THREAD

**Issue by masti10** [mandatoryprogrammer/TrustTrees#29]
Pretty new to the whole python, but tried to install your software.

The following command worked to install the software:
python3.7 -m pip install TrustTrees pygraphviz

When it complained about missing xmlrpclib, I installed xmlrpclib-1.0.1.zip from effbot.org

But now I'm seeing the below error:

$ trusttrees.py --help
Traceback (most recent call last):
 File "/usr/local/bin/trusttrees.py", line 19, in <module>
   import xmlrpclib
 File "/usr/local/lib/python3.7/site-packages/xmlrpclib.py", line 169
   MAXINT =  2L**31-1
              ^
SyntaxError: invalid syntax

How to fix it? I need the --resolvers argument(not found until 2.0.1 version??) to work. Appreciate your help.

More info:
OS= Centos 7
Has python, python2, python3 and python3.7 binaries in the path.

**Comment by KevinHock** [comment]
Sorry for the late reply.

Can you try again under Python 3 @masti10?

**Comment by KevinHock** [comment]
[From reading stackoverflow](https://stackoverflow.com/questions/22538535/how-to-make-downloaded-python-libs-work-on-windows), I think `import xmlrpclib` needed to be replaced with `import xmlrpc.client` at the time this issue was made. It has since been replaced so I should have closed this issue a while back.

Thank you for making this!
